#KAKAO API - QR

# src/main/resources/application.yml
kakao:
  pay:
    host: https://kapi.kakao.com
    admin-key: 69f7ee365f91f76f52dd07386013ecba # 실제 발급받은 관리자 키 #카카오 디벨롭 사이트에 있음
    cid: TC0ONETIME          # 가맹점 코드 (테스트용), 개발자가 만들어서 작성 X 저거 그대로 써야함
    ready-path: /payment/ready # 카카오페이 호출 주소, 개발자가 만들어서 작성 X 저거 그대로 써야함
    approve-path: /payment/approve # 카카오페이 인증 주소, 개발자가 만들어서 작성 X 저거 그대로 써야함